<?xml version="1.0" encoding="utf-8"?><testsuites><testsuite errors="0" failures="1" hostname="HASEE-PC" name="pytest" skipped="0" tests="3" time="0.051" timestamp="2020-07-10T14:29:39.933453"><testcase classname="testing.test_calc" file="testing\test_calc.py" line="6" name="test_add" time="0.000"></testcase><testcase classname="testing.test_calc" file="testing\test_calc.py" line="12" name="test_add1" time="0.001"></testcase><testcase classname="testing.test_calc" file="testing\test_calc.py" line="18" name="test_div" time="0.000"><failure message="assert 3 == -1
  +3
  --1">@pytest.mark.div
    def test_div():
        cal = Calculator()
&gt;       assert 3 == cal.div(1, 2)
E       assert 3 == -1
E         +3
E         --1

test_calc.py:22: AssertionError</failure></testcase></testsuite></testsuites>